version: '2'
networks:
  default: {}
services:
  mysql:
    container_name: mrphan_mysql_con
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    build:
      context: ./mysql
      args:
        - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
        - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
        - MYSQL_DATA_DIR=${MYSQL_DATA_DIR}
        - MYSQL_LOG_DIR=${MYSQL_LOG_DIR}
    ports:
      - "4306:3306"
    volumes:
      - ./mysql/logs:${MYSQL_LOG_DIR}
      - ./mysql/loging.cnf:/etc/mysql/conf.d/loging.cnf
      - ./mysql/data:${MYSQL_DATA_DIR}
    environment:
      MYSQL_DATABASE: keirinlocaldb
      MYSQL_USER: keirin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_RANDOM_ROOT_PASSWORD: "false"

  apache:
    container_name: mrphan_apache_con
    build:
      context: ./webserver
    ports:
      - "4000:80"
    volumes:
      - ${SOURCE_CODE_PATH}:/var/www/html/keirin_api
      - ./webserver/apache/logs:/var/log/httpd
    links:
      - mysql
    depends_on:
      - mysql
    env_file: .env